name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  checks: write
  contents: write
  id-token: write
  security-events: write

jobs:
  proj-ci:
    name: "CI"
    uses: ./.github/workflows/proj-ci.yaml
    secrets: inherit

  terraform-apply:
    name: "Terraform apply"
    needs: proj-ci
    secrets: inherit
    uses: ./.github/workflows/terraform-cd.yaml